name: Test - Build and Publish to Docker Hub

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag aaronweggemans/mortgage-calculator:latest
      - name: Push image to docker hub
        run: |
          docker login -u aaronweggemans -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push aaronweggemans/mortgage-calculator:latest
